site_name: Biologia i Geologia — 4t d'ESO
site_description: Materials de Biologia i Geologia de 4t d'ESO
site_url: https://saloma-ui.github.io/biogeo4/
repo_url: https://github.com/saloma-ui/biogeo4
repo_name: saloma-ui/biogeo4

language: ca

theme:
  name: material
  language: ca
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search
  - exporter:
      formats:
        pdf:
          explicit: true
          concurrency: 4

nav:
  - Inici: index.md
  - Programació:
      - Presentació: programacio/index.md
      - Criteris d'avaluació: programacio/criteris-avaluacio.md
      - Calendari: programacio/calendari.md
  - UD1:
      - Presentació: ud1/index.md
      - Temari: ud1/temari.md
  - UD2:
      - Presentació: ud2/index.md
      - Temari: ud2/temari.md
  - UD3:
      - Presentació: ud3/index.md
      - Temari: ud3/temari.md
  - UD4:
      - Presentació: ud4/index.md
      - Temari: ud4/temari.md
  - UD5:
      - Presentació: ud5/index.md
      - Temari: ud5/temari.md
  - UD6:
      - Presentació: ud6/index.md
      - Temari: ud6/temari.md
  - Activitats:
      - UD1:
          - Índex: activitats/ud1/index.md
          - G1 · Reconstruïm una història geològica: activitats/ud1/G1/G1_reconstruim_una_historia_geologica.md
          - G2 · On construiríem?:
              - Sessió 18: activitats/ud1/G2/g2_sessio_18.md
              - Sessió 19: activitats/ud1/G2/g2_sessio_19.md
      - UD2:
          - Índex: activitats/ud2/index.md
      - UD3:
          - Índex: activitats/ud3/index.md
      - UD4:
          - Índex: activitats/ud4/index.md
      - UD5:
          - Índex: activitats/ud5/index.md
      - UD6:
          - Índex: activitats/ud6/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - toc:
      permalink: true

extra_css:
  - assets/css/extra.css
