site_name: Biologia i Geologia — 4t d'ESO
site_description: Materials de Biologia i Geologia de 4t d'ESO
site_url: https://saloma-ui.github.io/biogeo4/
repo_url: https://github.com/saloma-ui/biogeo4
repo_name: saloma-ui/biogeo4

theme:
  name: material
  language: ca
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search
  - exporter:
      formats:
        pdf:
          explicit: true
          concurrency: 1
          browser:
            timeout: 120000

nav:
  - Inici: index.md
  - Informació del curs:
      - Programació: programacio.md
      - Criteris d'avaluació: criteris-avaluacio.md
      - Calendari: calendari.md
  - Material:
      - UD1: material/ud1/ud1.md
      - UD2: material/ud2/ud2.md
      - UD3: material/ud3/ud3.md
      - UD4: material/ud4/ud4.md
      - UD5: material/ud5/ud5.md
      - UD6: material/ud6/ud6.md
  - Activitats:
      - UD1:
          - Índex: activitats/ud1/index.md
          - G1 · Reconstruïm una història geològica: activitats/ud1/g1/g1.md
          - G2 · On construiríem?:
              - Sessió 18: activitats/ud1/g2/g2_sessio_18.md
              - Sessió 19: activitats/ud1/g2/g2_sessio_19.md
      - UD2:
          - Índex: activitats/ud2/index.md
      - UD3:
          - Índex: activitats/ud3/index.md
      - UD4:
          - Índex: activitats/ud4/index.md
      - UD5:
          - Índex: activitats/ud5/index.md
      - UD6:
          - Índex: activitats/ud6/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - toc:
      permalink: true

extra_css:
  - extra.css
