name: Publica el web amb MkDocs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descarrega el repositori
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instal·la dependències
        run: pip install -r requirements.txt

      - name: Publica amb MkDocs
        run: mkdocs gh-deploy --force
